### ISSUE TITLE
Makefile in image folder has bugs

### ISSUE THREAD

**Issue by djtulan** [hbekel/reprom64#1]
Hi!

I created an Image with the makefile, but the created image.bin is defect.
Character ROM and BASIC ROM areas are swappted.

**WRONG** 
OBJECTS=k0.bin k1.bin k2.bin k3.bin \
	c0.bin c1.bin c2.bin c3.bin \
	b0.bin b1.bin

**CORRECT**
OBJECTS=k0.bin k1.bin k2.bin k3.bin \
	b0.bin b1.bin \
	c0.bin c1.bin c2.bin c3.bin

**Comment by hbekel** [comment]
Thanks for reporting this, fixed in 8ef370fbd3d7d492e293d4fc54ac9b68f8305b8f
